### ISSUE TITLE
Deviance feature selection- increase speed

### ISSUE THREAD

**Issue by willtownes** [kstreet13/scry#12]
The current deviance feature selection implementation is slow. Improve the speed by vectorizing operations. The functions should support dense matrices, sparse Matrix objects, and dense DelayedArray/ HDF5Array objects.

**Comment by kstreet13** [comment]
Not sure if you've already started working on this (or if you have plans for accomplishing both goals simultaneously), but since the code for feature selection is pretty similar to `nullResiduals`, I could take a stab at getting it DelayedArray-ready.

**Comment by willtownes** [comment]
I already have the functions written, I just need to copy them into the repository and make them S4 compatible. I just wanted a reminder since I'm heavily distracted by making slides for bioc and JSM today and tomorrow.

**Comment by willtownes** [comment]
This is now implemented on develop branch: f130f73697a0780783eb2730453ef6204bf381d7
