### ISSUE TITLE
more than one "batch"

### ISSUE THREAD

**Issue by Hongru-Hu** [kstreet13/scry#16]
hi, I was wondering if there's any example to deal with "more than one batch" situation using the `devianceFeatureSelection()` function? for example I have "batch", "sex", "age" ... to be corrected.

**Comment by willtownes** [comment]
That is a good idea for an enhancement, however it is not currently implemented. If you are willing to consider the interaction between all covariates, you can collapse multiple categorical variables into a single factor and then use that. If you want to have additive effects, I believe this would no longer have a closed-form solution for the MLE (the same thing applies for continuous covariates). At that point what we would recommend is just running a separate Poisson regression for each gene then pulling the deviance from that.

**Comment by Hongru-Hu** [comment]
thank you!
