### ISSUE TITLE
Build error from Bioconductor

### ISSUE THREAD

**Issue by willtownes** [kstreet13/scry#19]
@kstreet13 was notified of a build error by the Bioconductor folks, quoting from his email:

> In the main vignette, there seems to be some problem loading the Zhengmix4eq dataset (though there are no issues with the DuoClustering2018 package, itself).
> 
> I'm unable to reproduce the error locally, but here's the build report: https://bioconductor.org/checkResults/devel/bioc-LATEST/scry/

It seems like the error only occurs with windows machines. I tried to reproduce the error (on a mac) but got a different one:
```
Error(s) in re-building vignettes:
    ...
  --- re-building ‘bigdata.Rmd’ using knitr
  Error: processing vignette 'bigdata.Rmd' failed with diagnostics:
  there is no package called ‘markdown’
  --- failed re-building ‘bigdata.Rmd’
  
  --- re-building ‘scry.Rmd’ using knitr
  Error: processing vignette 'scry.Rmd' failed with diagnostics:
  there is no package called ‘markdown’
  --- failed re-building ‘scry.Rmd’
```
The weird thing for my error is, the markdown package is installed, and I can build the vignettes with no issue if I build them directly, they failure only occurs when I try to do the build/check process.

**Comment by kstreet13** [comment]
For the record, this is the output of the build report on the Bioconductor Windows machine:
```
##############################################################################
##############################################################################
###
### Running command:
###
###   chmod a+r scry -R && F:\biocbuild\bbs-3.18-bioc\R\bin\R.exe CMD build --keep-empty-dirs --no-resave-data scry
###
##############################################################################
##############################################################################


* checking for file 'scry/DESCRIPTION' ... OK
* preparing 'scry':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building 'bigdata.Rmd' using knitr
--- finished re-building 'bigdata.Rmd'

--- re-building 'scry.Rmd' using knitr

Quitting from lines 27-30 [unnamed-chunk-2] (scry.Rmd)
Error: processing vignette 'scry.Rmd' failed with diagnostics:
failed to load resource
  name: EH1524
  title: sce_full_Zhengmix4eq
  reason: unknown input format
--- failed re-building 'scry.Rmd'

SUMMARY: processing the following file failed:
  'scry.Rmd'

Error: Vignette re-building failed.
Execution halted
```
I have no issues rebuilding the vignettes locally (on Mac).

**Comment by kstreet13** [comment]
This appears to have been resolved. Per Jennifer Wokaty's response on the bioc-devel mailing list:
> We removed resource EH1524 from the cache so it could be redownloaded. scry's report does not show errors today: https://bioconductor.org/checkResults/devel/bioc-LATEST/scry/.
