### ISSUE TITLE
Cleaning up old branches

### ISSUE THREAD

**Issue by willtownes** [kstreet13/scry#22]
@kstreet13 are you OK with me deleting the HDF5 branch? I think it is fully integrated into both develop and master. Also, I am going to bring the "develop" and "r3" branches up to date with "master". I will merge the pull request from eweine separately.

**Comment by kstreet13** [comment]
Yeah, sounds good!

**Comment by willtownes** [comment]
Done!

**Comment by kstreet13** [comment]
I also just noticed that we used Travis CI and it seems like it's broken. Let me know when you're done and I can update that to a GitHub Actions workflow.

**Comment by willtownes** [comment]
I'm finished for now, feel free to go ahead. After that I will try to merge the pull request.

**Comment by willtownes** [comment]
Oh and can you set it up to test that it builds on R 4.0/ 4.1/ 4.2 as well as 4.3? I'm embarrassed to admit I haven't learned GH actions yet.

**Comment by kstreet13** [comment]
I could be wrong, but I don't think we need to worry about that. Bioconductor releases are tied to specific versions of R, so if someone is running R 4.0, they shouldn't be able to install the latest version of `scry` (I've definitely encountered this sort of problem when I let my R installation get too out-of-date).

**Comment by willtownes** [comment]
OK, I changed the DESCRIPTION and README to say we require the latest version of R.
